name: code-quality

on: push

jobs:
  black:
    name: Check code formatting with black
    runs-on: ubuntu-latest

    steps:
      - name: Install libxml
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install -r requirements/base.txt
      - name: Run black
        run: |
          black --check --diff src
  isort:
    name: Check import sorting
    runs-on: ubuntu-latest

    steps:
      - name: Install libxml
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: isort/isort-action@v0.1.0
        with:
          requirementsFiles: requirements/base.txt
          sortPaths: "src"
          configuration: "--check-only --diff --profile black"
